# Generated by Django 4.0 on 2021-12-22 22:04

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': 'notices'},
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default=builtins.print, max_length=200),
            preserve_default=False,
        ),
    ]
