# Generated by Django 4.0 on 2021-12-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_boards', '0002_alter_notice_options_notice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
